

services:
  # API Service - Development overrides
  api:
    build:
      context: ./services/api
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      SENTRY_DSN: ""
    volumes:
      - ./services/api:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: npm run dev
    stdin_open: true
    tty: true

  # AI Service - Development overrides
  ai-service:
    build:
      context: ./services/ai
    environment:
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: DEBUG
      DEBUG: "1"
    volumes:
      - ./services/ai:/app
      - ai_models:/app/models
      - ./logs:/app/logs
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    stdin_open: true
    tty: true

  # Web Frontend - Development overrides
  web:
    build:
      context: ./apps/web
    environment:
      NODE_ENV: development
      VITE_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true

  # Mobile Development Server - Development overrides
  mobile:
    build:
      context: ./apps/mobile
    environment:
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      EXPO_PACKAGER_HOSTNAME: localhost
    volumes:
      - ./apps/mobile:/app
      - /app/node_modules
    command: npm start
    stdin_open: true
    tty: true

  # MongoDB - Development overrides
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: multimodal-platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Redis - Development overrides
  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO - Development overrides
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # Nginx - Disabled in development
  nginx:
    profiles:
      - production
