# Development overrides
services:
  # Backend API Service - Development overrides
  backend:
    build:
      context: ./backend
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    command: npm run dev

  # AI Service - Development overrides
  ai-service:
    build:
      context: ./ai_service
      target: development
    environment:
      ENVIRONMENT: development
      LOG_LEVEL: debug
      CORS_ORIGIN: http://localhost:3000
    volumes:
      - ./ai_service:/app
      - ./ai_service/models:/app/models
      - ./ai_service/logs:/app/logs
      - ./ai_service/uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Web App - Development overrides
  frontend:
    build:
      context: ./frontend
      target: development
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_AI_SERVICE_URL: http://localhost:8000
      NEXT_PUBLIC_WS_URL: ws://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Nginx - Development overrides (disable SSL)
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
