version: '3.8'

services:
  # API Service - Development Override
  api:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ./services/api:/app
      - /app/node_modules
    command: npm run dev

  # AI Service - Development Override
  ai-service:
    build:
      target: development
    environment:
      PYTHONPATH: /app
      LOG_LEVEL: debug
    volumes:
      - ./services/ai:/app
      - ai_models:/app/models
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Web Frontend - Development Override
  web:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Mobile Development Server - Development Override
  mobile:
    build:
      target: development
    environment:
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./apps/mobile:/app
      - /app/node_modules
    command: npm start

  # MongoDB - Development Override
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"

  # Redis - Development Override
  redis:
    ports:
      - "6379:6379"

  # MinIO - Development Override
  minio:
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"

  # Nginx - Development Override (Simplified)
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.dev.conf:/etc/nginx/nginx.conf

  # Prometheus - Development Override
  prometheus:
    ports:
      - "9090:9090"

  # Grafana - Development Override
  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    ports:
      - "3002:3000"
