version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  api:
    build: ./services/api
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./services/api:/app
      - /app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - mongo
      - redis
      - minio

volumes:
  mongo_data:
  minio_data:


