global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8000']
    metrics_path: '/metrics'

  - job_name: 'api-service'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'

  - job_name: 'web-frontend'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/metrics'
