name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/vision-platform:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/vision-platform:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy vision-platform \
            --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/vision-platform:${{ github.sha }} \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated
      - name: Run MongoDB migrations on Atlas
        env:
          MONGODB_URI: ${{ secrets.MONGODB_ATLAS_URI }}
        run: |
          docker run --rm -e MONGODB_URI=${{ secrets.MONGODB_ATLAS_URI }} -v ${{ github.workspace }}/scripts:/scripts node:20 node /scripts/migrate_mongodb.js "$MONGODB_URI"
      - name: Smoke test
        run: |
          curl -f ${{ secrets.CLOUD_RUN_URL }}/healthz
